name: Build all practical-m-files projects

on:
  workflow_dispatch:
  push:
    paths: ["src/**"]

jobs:
  build:
    timeout-minutes: 15
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore src\vaultapplication\vaultapplication-cleanarch\vaultapplication-cleanarch.sln

    - name: Set timezone on Windows to Central Europe Standard Time
      run: tzutil /s "Central Europe Standard Time"

    - name: Build vaultapplication-cleanarch
      run: msbuild src\vaultapplication\vaultapplication-cleanarch\vaultapplication-cleanarch.sln /nologo /verbosity:m /p:Configuration=Release /p:DefineConstants="DONOTDEPLOY"
      
      