name: Build all practical-m-files projects

on:
  workflow_dispatch:
  push:
    paths: ["src/**"]

jobs:
  build:
    timeout-minutes: 15
    runs-on: 'windows-latest'
    strategy:
      matrix: 
        solution: [ "src/**/*.sln" ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    # Restore NuGet packages
    - name: Restore NuGet packages ${{ matrix.solution }}
      run: nuget restore ${{ matrix.solution }}

    - name: Set timezone on Windows to Central Europe Standard Time
      run: tzutil /s "Central Europe Standard Time"

    # Build projects
    - name: Build ${{ matrix.solution }}
      run: msbuild ${{ matrix.solution }} /nologo /verbosity:m /p:Configuration=Release /p:DefineConstants="DONOTDEPLOY"
