name: Build all practical-m-files projects

on:
  workflow_dispatch:
  push:
    paths: ["src/**"]

jobs:
  build:
    timeout-minutes: 15
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    # Restore NuGet packages
    - name: Restore NuGet packages vaultapplication-cleanarch
      run: nuget restore src\vaultapplication\vaultapplication-cleanarch\vaultapplication-cleanarch.sln

    - name: Restore NuGet packages vaultapplication-logtomsteams-with-serilog
      run: nuget restore  src\vaultapplication\vaultapplication-logtomsteams-with-serilog\vaultapplication-logtomsteams-with-serilog.sln

    - name: Restore NuGet packages vaultapplication-mediatr
      run: nuget restore  src\vaultapplication\vaultapplication-mediatr\vaultapplication-mediatr.sln

    - name: Restore NuGet packages vaultapplication-net48
      run: nuget restore  src\vaultapplication\vaultapplication-net48\vaultapplication-net48.sln

    - name: Restore NuGet packages vaultapplication-reporttoeventlog-with-serilog
      run: nuget restore  src\vaultapplication\vaultapplication-reporttoeventlog-with-serilog\vaultapplication-reporttoeventlog-with-serilog.sln

    - name: Restore NuGet packages vaultapplication-unittestable-usecase
      run: nuget restore  src\vaultapplication\vaultapplication-unittestable-usecase\vaultapplication-unittestable-usecase.sln

    - name: Set timezone on Windows to Central Europe Standard Time
      run: tzutil /s "Central Europe Standard Time"

    # Build projects
    - name: Build vaultapplication-cleanarch
      run: msbuild src\vaultapplication\vaultapplication-cleanarch\vaultapplication-cleanarch.sln /nologo /verbosity:m /p:Configuration=Release /p:DefineConstants="DONOTDEPLOY"

    - name: Build vaultapplication-logtomsteams-with-serilog
      run: msbuild src\vaultapplication\vaultapplication-logtomsteams-with-serilog\vaultapplication-logtomsteams-with-serilog.sln /nologo /verbosity:m /p:Configuration=Release /p:DefineConstants="DONOTDEPLOY"
      
    - name: Build vaultapplication-mediatr
      run: msbuild src\vaultapplication\vaultapplication-mediatr\vaultapplication-mediatr.sln /nologo /verbosity:m /p:Configuration=Release /p:DefineConstants="DONOTDEPLOY"
      
    - name: Build vaultapplication-net48
      run: msbuild src\vaultapplication\vaultapplication-net48\vaultapplication-net48.sln /nologo /verbosity:m /p:Configuration=Release /p:DefineConstants="DONOTDEPLOY"
      
    - name: Build vaultapplication-reporttoeventlog-with-serilog
      run: msbuild src\vaultapplication\vaultapplication-reporttoeventlog-with-serilog\vaultapplication-reporttoeventlog-with-serilog.sln /nologo /verbosity:m /p:Configuration=Release /p:DefineConstants="DONOTDEPLOY"
      
    - name: Build vaultapplication-unittestable-usecase
      run: msbuild src\vaultapplication\vaultapplication-unittestable-usecase\vaultapplication-unittestable-usecase.sln /nologo /verbosity:m /p:Configuration=Release /p:DefineConstants="DONOTDEPLOY"
